# permissions for end users to edit tests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: learn-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: test-editor-role
rules:
- apiGroups:
  - test.abhi.go
  resources:
  - tests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.abhi.go
  resources:
  - tests/status
  verbs:
  - get
